// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uusgasfyjxcophsrwzsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1c2dhc2Z5anhjb3Boc3J3enNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDEzMDksImV4cCI6MjA2Mzc3NzMwOX0.qNiGTIWpYLYUxFmHXwRrkr30eXW4CJToSzTyg4N7dos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);